spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: link.toocool.vacancydiary.configuration.CustomPostgreSQL9Dialect
  flyway:
    baseline-on-migrate: true
    out-of-order: true
    ignore-missing-migrations: true
  output:
    ansi:
      enabled: always

server:
  port: 80